apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: profile-service
  labels:
    app: profile
spec:
  type: NodePort
  ports:
  - port: 8080
    name: profile
    targetPort: 8080
    nodePort: 30123
  selector:
    app: profile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: profile
  name: profile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - image: piotrporzucek/profile
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        name: profile
     
